# Site settings
title: Things of Interest
email: castinginterest@gmail.com
description: "Things of Interest is hosted by Serena Chen and Sophia Frentz, and is a podcast that encompasses, in its purest form, things that we find interesting. Our discussions often center around technological advancements and how they affect social issues. As two socially-conscious millennial nerds, who is better placed to talk about artificial intelligence, leadership, modern dating, the job market, and fandom? Probably no-one."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.thingsofinterest.co"
twitter_username: castinginterest
github_username:  heisenburger

# Build settings
markdown: kramdown

# Podcast General Settings
podcastSite: http://www.thingsofinterest.co
podcastCoverImg: http://www.thingsofinterest.co/images/toi-cover.png
podcastTitle: Things of Interest
podcastOwner: "Serena Chen &amp; Sophia Frentz"
podcastEmail: castinginterest@gmail.com
# podcastIsExplicit: "yes"

podcastAuthor: "Serena Chen &amp; Sophia Frentz"
podcastDescription: "Things of Interest is hosted by Serena Chen and Sophia Frentz, and is a podcast that encompasses, in its purest form, things that we find interesting. Our discussions often center around technological advancements and how they affect social issues. As two socially-conscious millennial nerds, who is better placed to talk about artificial intelligence, leadership, modern dating, the job market, and fandom? Probably no-one."
podcastSubtitle: Non-feminist topics through a feminist lens.
