# Site settings
title: Things of Interest
email: castinginterest@gmail.com
description: Two nerds having great chats across the Tasman. Non-feminist topics through a feminist lens.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thingsofinterest.co" # the base hostname & protocol for your site
twitter_username: castinginterest
github_username:  heisenburger

# Build settings
markdown: kramdown

# Podcast General Settings
podcastSite: http://thingsofinterest.co
podcastCoverImg: http://thingsofinterest.co/images/toi-cover.png
podcastTitle: Things of Interest
podcastOwner: Serena Chen &amp; Sophia Frentz
podcastEmail: castinginterest@gmail.com
category: 
- Society &amp; Culture
podcastIsExplicit: "yes"

podcastAuthor: Serena Chen &amp; Sophia Frentz
podcastDescription: Two nerds having great chats across the Tasman. Non-feminist topics through a feminist lens.
podcastSubtitle: Non-feminist topics through a feminist lens.
